spring.application.name=First-Rest-API-Spring
spring.h2.console.enabled=true
spring.h2.console.path=/console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
logging.level.org.hibernate.SQL=DEBUG

# REST API Port
server.port=${PORT:8080}
# gRPC Port
grpc.server.port=${GRPC_PORT:9090}

# Disable TLS (encryption) for local benchmarking ? simpler setup
grpc.server.security.enabled=false

# Address of the Pulsar broker started via Docker
pulsar.service-url=${PULSAR_URL:pulsar://localhost:6650}

# Request topic: benchmark sends product fetch requests here
pulsar.topic.request=persistent://public/default/product-request
# Reply topic: service sends responses back here
pulsar.topic.reply=persistent://public/default/product-reply