spring.application.name=First-Rest-API-Spring
spring.h2.console.enabled=true
spring.h2.console.path=/console
spring.datasource.url=jdbc:h2:mem:testdb
logging.level.org.hibernate.SQL=DEBUG

# REST API Port
server.port=${PORT:8080}
# gRPC Port
grpc.server.port=9090

# Disable TLS (encryption) for local benchmarking ? simpler setup
grpc.server.security.enabled=false